// src/app/api/ai/extract-resume-data/route.ts
import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export async function POST(req: Request) {
  try {
    // Check authentication
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Parse request body
    const { prompt, jobTitle, company } = await req.json();

    if (!prompt) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 }
      );
    }

    // Call AI model to extract resume data (example using OpenAI)
    // Note: Replace with your actual AI implementation

    // Sample response structure for frontend development
    const resumeData = {
      title: `Resume for ${jobTitle || "New Position"}`,
      jobTitle: jobTitle || "",
      companyTargeted: company || "",
      personalInfo: {
        name: "Alex Johnson", // This would be generated by AI
        email: "alex.johnson@example.com",
        phone: "(555) 123-4567",
        location: "San Francisco, CA",
        linkedin: "linkedin.com/in/alexjohnson",
      },
      summary:
        "Results-driven professional with expertise in software development, project management, and team leadership. Skilled in developing innovative solutions that meet business requirements and enhance user experience.",
      experience: [
        {
          company: "TechSolutions Inc.",
          position: "Senior Frontend Developer",
          location: "San Francisco, CA",
          startDate: new Date("2021-01-15"),
          current: true,
          responsibilities: [
            "Lead the development of responsive web applications using React and TypeScript",
            "Improved site performance by 40% through code optimization and lazy loading",
            "Mentored junior developers and conducted code reviews",
          ],
        },
        {
          company: "WebCraft Studios",
          position: "Frontend Developer",
          location: "Austin, TX",
          startDate: new Date("2018-06-01"),
          endDate: new Date("2020-12-31"),
          responsibilities: [
            "Developed interactive web applications using React and Redux",
            "Implemented CI/CD pipelines that reduced deployment time by 70%",
            "Created reusable UI components following atomic design principles",
          ],
        },
      ],
      education: [
        {
          institution: "University of Texas at Austin",
          degree: "Bachelor of Science",
          fieldOfStudy: "Computer Science",
          startDate: new Date("2014-09-01"),
          endDate: new Date("2018-05-15"),
          gpa: "3.8/4.0",
        },
      ],
      skills: [
        "JavaScript",
        "TypeScript",
        "React",
        "Node.js",
        "HTML/CSS",
        "Redux",
        "GraphQL",
        "Jest",
        "Webpack",
        "Git",
        "CI/CD",
      ],
      projects: [
        {
          name: "E-commerce Dashboard",
          description:
            "Built a comprehensive admin dashboard for e-commerce businesses with real-time analytics.",
          technologies: "React, Redux, Node.js, MongoDB",
          url: "https://github.com/alexjohnson/ecommerce-dashboard",
        },
      ],
    };

    // Return the extracted data
    return NextResponse.json({
      success: true,
      resumeData,
    });
  } catch (error) {
    console.error("Error extracting resume data:", error);
    return NextResponse.json(
      { error: "Failed to extract resume data" },
      { status: 500 }
    );
  }
}
